### ISSUE TITLE
Curious Question About Controllers [Not a Bug]

### ISSUE THREAD

**Issue by AdamKyle** [thewunder/croute#3]
Why did you tie your routing system to a specific way of setting up controllers and not just allow a developer to set up there own controller base?

**Comment by thewunder** [comment]
All that is required is that they implement ControllerInterface, which contains just two methods.  It is a reasonable assumption that the controller would want access to the whole http request.  This requirement also prevents classes that were not intended for use as a controller from be loaded.

The Controller class and it's methods are purely for convenience.
